### ISSUE TITLE
Question: Is it possible to use with external styles?

### ISSUE THREAD

**Issue by unleashit** [kevin940726/svg-css-modules-loader#3]
I could be missing something, but is it possible to set this up to work with an external style sheet? I'm more than beginner but not advanced with Webpack and I'm not sure how one would sync the class name transformations of an external stylesheet with the transformations made by this module. What I'm trying to accomplish is basically:

```
// mySVG.svg

<svg ...>
  <circle class="my-circle" cx="-88.9" cy="397" r="98.2"/>
  ...
</svg>


// home.scss

.heading { color: purple; }
.my-circle { fill: red; } // currently outputs with different filename and hash from the SVG


// home.js

import { heading } from './homeStyles.scss';
import mySVG from './mySVG.svg';

const Home = () => {
  return (
    <div>
      ...
      <h1 className={heading}>Welcome!</h1>  // resulting class is transformed and matches the one in the scss file
      <mySVG />  // class names are transformed but not sure how to match up with a scss file or even target from global CSS since the hashes are random with each build
    </div>
  );
}

```
Is there a way to get the css module transformations of both home.scss and the svg to match up? I'm currently using this loader with react-svg-loader to create an inline SVG component and run SVGO.

I don't expect this to happen automagically, but is there a way I can configure it? Or is the point of svg-css-modules-loader only to create a namespace for inline styles directly inside the SVG? The latter isn't what I need since I need to dynamically alter for user events, media queries, etc., plus it's easier to maintain CSS outside the SVG.

**Comment by kevin940726** [comment]
I believe this can be done with `localIdentName` option. Just that you cannot use hash which is included in the default setting.

```diff
- loader: 'svg-react!svgo!svg-css-modules'
+ loader: 'svg-react!svgo!svg-css-modules?localIdentName=[name]__[local]'
```

And you can select the class name beforehand.

```css
.myFileName__my-circle { fill: red; }
```

I actually have never tried it, tell me whether it works for you. Or if it's not, I'll be really grateful if you can send a PR :wink: . Thanks for your feedback, I really appreciate it.

**Comment by unleashit** [comment]
Thanks for your reply. I thought of that, and while it isn't perfect I may end up utilizing it sometimes. After giving it some more thought, I think maybe the only way to achieve class names that are encapsulated to the module (not file) like [component name]__[class name]__[hash], would be to assign them inline to a React component version of the SVG. To avoid a ton of manual work, that would best be part of a package that transforms SVG to components. 

I'm new to CSS modules, and just found out today :global exists. So right now I'm able to achieve at least something close to what I'm looking for in two ways. 

Without svg-css-modules-loader in an scss file imported with CSS Modules turn on:

```
.logo {
  :global .st5 {
    fill:#51B748;
  }
}
// result is .home__logo__[hash] .st5  --> no transformation on the child, but still very specific
```
The second way being the loader and your suggestion. Here we're just dealing with normal global styles that can be targeted from anywhere (even with CSS modules on if you wrap it in global). This is a good thing in my opinion for icons and SVG that are going to be reused elsewhere. For this use, I like that your loader basically can add the B of BEM to the class names and make them a bit harder (although not impossible) to collide with something. Thanks for your work so far and feel free to close this if you like.
